# Python CircleCI 2.0 configuration file
version: 2
jobs:
  build:
    docker:
      - image: circleci/python:3.6.8
    working_directory: ~/repo
    steps:
      - checkout
      - run:
          name: permissions setup
          command: |
            sudo chown -R circleci:circleci /usr/local/bin
            sudo chown -R circleci:circleci /usr/local/lib/python3.6/site-packages
      - restore_cache:
          keys:
            - cache-data-{{ .Branch }}-{{ checksum "Pipfile.lock" }}
            - cache-data-{{ .Branch }}-
            - cache-data-
      - run:
          name: install dependencies
          command: |
            sudo pip install pipenv
            pipenv install --dev
      - save_cache:
          key: cache-data-{{ .Branch }}-{{ checksum "Pipfile.lock" }}
          paths:
            - "/usr/local/bin"
            - "/usr/local/lib/python3.6/site-packages/"
            - "/home/circleci/.local/share/virtualenvs/"
      - run:
          name: run tests
          command: |
            pipenv run coverage run --source=. -m pytest
            pipenv run coverage html
            pipenv run coverage report
      - store_artifacts:
          path: htmlcov
